// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrayerTimes.Data;

namespace PrayerTimes.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210102040757_updateDb")]
    partial class updateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrayerTimes.Models.Prayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrayerTimetableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrayerTimetableId");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("PrayerTimes.Models.PrayerTimetable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrayerTimetables");
                });

            modelBuilder.Entity("PrayerTimes.Models.Prayer", b =>
                {
                    b.HasOne("PrayerTimes.Models.PrayerTimetable", "PrayerTimetable")
                        .WithMany("Prayers")
                        .HasForeignKey("PrayerTimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
